### ISSUE TITLE
Review-2 Suggestion To be Implemented.

### ISSUE THREAD

**Issue by Ammar2123** [Bigg-Chungus-Group/Scriptopia#31]
1. Implement a faculty certification system to manage and maintain faculty records.
2. Create a timer or expiration system to track the validity of certifications
3. Change the Leaderboard name of the house (as due by HOD sir).
4. Add a feature for faculty (house coordinators) to allocate badges to students.
5. Provide an option to download a report for students, displaying the certificates they've uploaded during the B.E program.
6. Implement academic year-wise segregation of certificates.
7. Allow faculty to view certificates without downloading them.

Acceptance Criteria:

1. Faculty certification system is developed and integrated.
2. The timer/expiration system is in place and notifies users of certification validity.
3. Leaderboard name change functionality is added and approved by HOD.
4. Faculty can allocate badges to students.
5. Students / Faculties can download a report of their uploaded certificates.
6. Certificates are organized by academic year.
7. Faculty can view certificates without downloading.

**Comment by annuraggg** [comment]
Fixed
